apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-ebs-claim  # Changed name
  namespace: three-tier
spec: 
  accessModes:  
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi